### ISSUE TITLE
certificates for SSL usage

### ISSUE THREAD

**Issue by hexabyte23** [addisonElliott/HttpServer#1]
Good piece of code. Is it possible to have a test using SSL ?

**Comment by addisonElliott** [comment]
Thanks.

Yes it's entirely possible. I'm happy to accept a PR if you're willing to do so. I would just generate a cert/private key and change the test code to utilize it. Maybe add a config option to enable/disable SSL.

**Comment by hexabyte23** [comment]
Ok, I try to do so. Could you first generate corresponding cert/key. I do not know how to do ?

**Comment by addisonElliott** [comment]
The best option is to google for a tutorial to do it. Search for generating a self-signed certificate

**Comment by hexabyte23** [comment]
Sorry I do not succeed to make things run.
I choose https://github.com/kingkool68/generate-ssl-certs-for-local-development as exemple

That generate 3 files:
local.dev.crt
local.dev.key
local.devCA.pem

in code I write

      config.sslKeyPath = "./certs/local.dev.key";
      config.sslCertPath = "./certs/local.dev.crt";
      config.sslKeyPassPhrase = "MyPass";

at start I get this log
Successfully setup SSL configuration, HTTPS enabled (../rcs/thirdparty/HttpServer/src/httpServer/httpServer.cpp:95, void HttpServer::loadSslConfig())

but my brave browser complain:

Your connection is not private
Attackers might be trying to steal your information from localhost (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_REVOKED

**Comment by addisonElliott** [comment]
The error message you received is a bit odd, but it is unsurprising that you get an error when using a self-signed certificate. Browsers will complain about self-signed certificates, although if you're testing a REST API, there is an option in Postman to allow self-signed certificates.

Try to do this using cURL or Postman and disable verifying certificates.

**Comment by hexabyte23** [comment]
I found the problem, on OS X self-signed certificates must be set to 'always trusted' with access.app. It's ok now
