### ISSUE TITLE
Async endpoint blocking threads

### ISSUE THREAD

**Issue by jcfain** [addisonElliott/HttpServer#12]
Hey thanks for this server. It works great!

One of my endpoints is a hls endpoint. 
It uses `QFile.read(qint64 maxlen)` to read a chunk of data to send back to the front end.

When it comes time to read the chunk other threads in my application get blocked. 
I am reading from a network share but I wouldn't think it would matter if its async.

I use the async method in your examples
`    return HttpPromise::resolve(data).then([this](HttpDataPtr data) {...});`

But the threads still get blocked.
Could it be something I'm doing or an issue?

Thanks again!

**Comment by addisonElliott** [comment]
Glad you're getting use out of it!

If I understand correctly, you're referencing this example: https://github.com/addisonElliott/HttpServer/blob/master/test/requestHandler.cpp#L162-L182

The thing to note about that example is it's not multithreaded. In other words, that logic is all ran on a single thread. The key thing to note is that Qt uses non-blocking networking methods and interconnects the Qt event loop with them.

I think the issue you're having is that `QFile` is synchronous unlike `QTimer` in my example.

`HttpPromise` should be safe to use in a multi-threaded environment. I've done this in the past and it worked great.

**Comment by addisonElliott** [comment]
To add onto this, there's a few ways to go about multithreading in Qt. See here for details: https://doc.qt.io/qt-5/threads-technologies.html

Here's how I've done it in one of my applications that uses `QtPromise`. For some background, I had some synchronous functions that I wanted to run asynchronously to prevent performance issues. See the code snippet below.

The magic in this is the `execAsyncPromise` function which essentially runs synchronous logic on a separate thread and returns a promise.

```cpp
class WorkerThread : public QObject
{
    Q_OBJECT

private:
    QThread thread;
    Worker worker;

    // Helper function that executes a function in the worker thread and resolves/rejects a QPromise when
    // the operation is finished
    template <typename Func, typename ...Args>
    QPromise<void> execAsyncPromise(Func &&func, Args &&...args)
    {
        return QPromise<void>{[&](
            const QtPromise::QPromiseResolve<void> &resolve,
            const QtPromise::QPromiseReject<void> &reject) {

            QMetaObject::invokeMethod(&worker, [=]() {
                try
                {
                    std::invoke(func, &worker, args...);
                    resolve();
                }
                catch (...)
                {
                    reject(std::current_exception());
                }
            }, Qt::QueuedConnection);
        }};
    }

public:
    WorkerThread();
    ~WorkerThread();

    // Commands to execute via worker thread
    QPromise<void> setControllersOffline();
    QPromise<void> setControllerOffline(QString serialNum);
    QPromise<void> updateControllerLastReadTime(QString serialNum, QDateTime timestamp,
        std::vector<int> installedNodeIDs);
    QPromise<void> updateControllerLastReadTime(QString serialNum, QDateTime timestamp);
    QPromise<void> updateControllerAuthCode(QString serialNum, QString authCode);
    QPromise<void> upsertController(QString serialNum, QString authCode);
};
```

```cpp
#include "workerThread.h"

Worker::Worker()
{

}

void Worker::setup()
{
    // Synchronous code here
}

void Worker::setControllersOffline()
{
    // Synchronous code here
}

void Worker::setControllerOffline(QString serialNum)
{
    // Synchronous code here
}

void Worker::updateControllerLastReadTimeRCM(QString serialNum, QDateTime timestamp,
    std::vector<int> installedNodeIDs)
{
    // Synchronous code here
}

void Worker::updateControllerLastReadTime(QString serialNum, QDateTime timestamp)
{
    // Synchronous code here
}

void Worker::updateControllerAuthCode(QString serialNum, QString authCode)
{
    // Synchronous code here
}

void Worker::upsertController(QString serialNum, QString authCode)
{
    // Synchronous code here
}

Worker::~Worker()
{
    if (redis)
        delete redis;
}

WorkerThread::WorkerThread()
{
    worker.moveToThread(&thread);
    connect(&thread, &QThread::started, &worker, &Worker::setup);

    thread.start();
}

QPromise<void> WorkerThread::setControllersOffline()
{
    return execAsyncPromise(&Worker::setControllersOffline);
}

QPromise<void> WorkerThread::setControllerOffline(QString serialNum)
{
    return execAsyncPromise(&Worker::setControllerOffline, serialNum);
}

QPromise<void> WorkerThread::updateControllerLastReadTime(QString serialNum, QDateTime timestamp,
    std::vector<int> installedNodeIDs)
{
    return execAsyncPromise(&Worker::updateControllerLastReadTimeRCM, serialNum, timestamp, installedNodeIDs);
}

QPromise<void> WorkerThread::updateControllerLastReadTime(QString serialNum, QDateTime timestamp)
{
    return execAsyncPromise(&Worker::updateControllerLastReadTime, serialNum, timestamp);
}

QPromise<void> WorkerThread::updateControllerAuthCode(QString serialNum, QString authCode)
{
    return execAsyncPromise(&Worker::updateControllerAuthCode, serialNum, authCode);
}

QPromise<void> WorkerThread::upsertController(QString serialNum, QString authCode)
{
    return execAsyncPromise(&Worker::upsertController, serialNum, authCode);
}

WorkerThread::~WorkerThread()
{
    thread.quit();
    thread.wait();
}
```

**Comment by jcfain** [comment]
Awesome thanks again!

I tried something like that (I dont think it was super close though) but has issues with compiling. Something about QPromise<std::shared_ptr<HttpData>>;

But now that I know it is possible and not an issue I can continue searching for how I can do it.
I will study your code and continue on this issue as soon as I can. 
Thanks for taking the time to give me this start!
