### ISSUE TITLE
Possible crash in HttpConnection::~HttpConnection()

### ISSUE THREAD

**Issue by marcolaz** [addisonElliott/HttpServer#8]
Executing 

```
HttpConnection::~HttpConnection()
{
    delete timeoutTimer;
    delete socket;
    ...

```
if the socket is active then the function **HttpConnection::socketDisconnected()** gets called, that in turn tries to call **timeoutTimer->stop()**, that was just destroyed.

Suggest to change the order of destruction, and for better security to disconnect all from socket:

```
HttpConnection::~HttpConnection()
{
    disconnect(socket);
    delete socket;
    delete timeoutTimer;
    ...

```

**Comment by addisonElliott** [comment]
Yeah, that's definitely a problem.

Another way to solve this is by using a signal blocker for `socket`. The question is whether `HttpConnection::socketDisconnected` should be called in the destructor.

Which brings up an even more interesting case, what about `HttpServer::connectionDisconnected`: https://github.com/addisonElliott/HttpServer/blob/promises/src/httpServer/httpServer.cpp#L159-L173

If deleting a connection, it will emit the `disconnected` and cause a segfault.

**Comment by marcolaz** [comment]
Yes, even in that case I would write:

```
    for (HttpConnection *connection : connections)
    {
        QObject::disconnect(connection);
        delete connection;
    }
```

(I am not used to use signal blockers, maybe it has the same effect)

**Comment by marcolaz** [comment]
Even better:

```
HttpConnection::~HttpConnection()
{
    socket->abort();    // Emit any signal before destructing receivers
    delete socket;
    delete timeoutTimer;
    ...

```

**Comment by addisonElliott** [comment]
Signal blockers are pretty simple. There's likely minimal performance implications between disconnecting the slot and blocking the signal.

The code would be:
```
QSignalBlocker (connection);
delete connection;
```

But, the other problem case still exists.

1. User deletes connection.
2. HttpConnection destructor calls `HttpConnection ::socketDisconnected`
3. `HttpConnection ::socketDisconnected` emits `disconnected` signal
4. `HttpServer::connectionDisconnected` is called via signal.
5. `HttpServer::connectionDisconnected` calls `connection->deleteLater()` which will segfault. Right?

**Comment by addisonElliott** [comment]
And, the `disconnected` signal should be emitted because that removes it from the connection list in `HttpServer` class. We just need to indicate that it doesn't need to be deleted somehow.

**Comment by marcolaz** [comment]
Calling

`socket->abort();`

should resolve both cases: connection->deleteLater() has no effect if we delete the QObject before re-entering the event loop

**Comment by addisonElliott** [comment]
👍 Sounds good. I'm on board with this change.

If you submit a PR, I'll accept.

Otherwise, I'll do this at some point (no idea when)

**Comment by marcolaz** [comment]
To submit a pull request I need write access to create a new branch in the repository.
I will gladly do it.

**Comment by addisonElliott** [comment]
Thanks. Just go ahead and fork this repository. Then you should be able to create a new branch and submit a PR.

**Comment by ragnar-lodbrok** [comment]
Please fix it in the master branch as well. Thanks.
